trigger:
- master
pool:
  name: "Hosted Windows 2019 with VS2019"
 
steps:
- task: AzurePowerShell@5
  displayName: 'RBAC User Assignments'
  inputs:
    azureSubscription: 'Internal Subscription 1(d7cc508e-d2cc-46d7-8185-5b4cb24827bb)'
    ScriptType: 'FilePath'
    ScriptPath: '$(Build.SourcesDirectory)\New-RBACRoleFromSource.ps1'
    ScriptArguments: '-ImportCsv $(Build.SourcesDirectory)\users.csv'
    errorActionPreference: 'silentlyContinue'
    azurePowerShellVersion: 'LatestVersion'